import type { Question, Reto, Dimension, ProfileMeta, DimensionKey, ProfileKey } from "./types";

export const TOTAL_QUESTIONS = 12;

export const DIM: Record<DimensionKey, Dimension> = {
  A: { name: "Decidir con datos",                  short: "Bloque I",   color: "#127334", bg: "#E4F1CF", dark: "#127334" },
  B: { name: "Conocimiento del equipo",             short: "Bloque II",  color: "#359E52", bg: "#E4F1CF", dark: "#127334" },
  C: { name: "Decisiones coordinadas",              short: "Bloque III", color: "#359E52", bg: "#E4F1CF", dark: "#127334" },
  D: { name: "Visión en tiempo real de dirección",  short: "Bloque IV",  color: "#9BBF64", bg: "#E4F1CF", dark: "#127334" },
};

export const RETOS: Reto[] = [
  { code: "01_1", dim: "A", name: "Análisis predictivo 360",
    sit: "Los costes y el impacto ambiental se calculan por separado y de forma reactiva.",
    obj: "Sincronizar ratios económicos y de sostenibilidad (CO₂, energía, agua) desde la ideación del activo." },
  { code: "01_2", dim: "A", name: "Aprender de lo que ya has hecho",
    sit: "Cada proyecto se presupuesta desde cero, ignorando la experiencia previa.",
    obj: "Validar la viabilidad de la inversión comparando automáticamente con el histórico de proyectos de la compañía." },
  { code: "01_3", dim: "A", name: "Control preventivo de desvíos",
    sit: "La detección de errores ocurre en el tajo, cuando el impacto económico ya es inevitable.",
    obj: "Implementar alertas tempranas que detecten riesgos técnicos antes de que afecten al margen de ejecución." },
  { code: "01_4", dim: "A", name: "Cumplimiento de Taxonomía EU",
    sit: "El reporte ESG es un proceso manual, costoso y propenso a errores de auditoría.",
    obj: "Automatizar la generación de indicadores técnicos (DNSH) y financieros (CapEx/OpEx) exigidos por la normativa europea." },
  { code: "02_1", dim: "B", name: "Institucionalización del patrimonio de datos",
    sit: "El conocimiento reside en la memoria de técnicos clave; si ellos se van, la empresa se descapitaliza.",
    obj: "Estructurar el histórico de proyectos en un modelo semántico accesible para toda la organización." },
  { code: "02_2", dim: "B", name: "Agilidad decisional con IA",
    sit: "El análisis de pliegos y normativas consume semanas de trabajo manual de perfiles expertos.",
    obj: "Emplear asistentes de IA para procesar documentación técnica y normativa en segundos, ganando velocidad competitiva." },
  { code: "02_3", dim: "B", name: "Auditoría de desempeño",
    sit: "No existe un cierre de ciclo; los errores de presupuesto en la obra A se repiten en la oferta de la obra B.",
    obj: "Alimentar automáticamente las bases de precios futuras con los costes reales y lecciones aprendidas de las obras actuales." },
  { code: "03_1", dim: "C", name: "Unidad de información — verdad única",
    sit: "Propiedad, Arquitectura y Constructora manejan versiones de archivos distintas.",
    obj: "Operar sobre un entorno de datos único donde cualquier cambio sea trazable para todos los agentes." },
  { code: "03_2", dim: "C", name: "Escalabilidad operativa",
    sit: "La calidad de la gestión varía según el equipo asignado al proyecto.",
    obj: "Homogeneizar los procesos mediante tarjetas de procedimiento estándar que garanticen la excelencia en toda la cartera." },
  { code: "03_3", dim: "C", name: "Trazabilidad de decisiones técnicas",
    sit: "Ante un siniestro o cambio, no hay registro claro de quién aprobó qué modificación y por qué.",
    obj: "Blindar la seguridad jurídica del activo mediante un historial inalterable de responsabilidades técnicas." },
  { code: "04_1", dim: "D", name: "Visibilidad consolidada de cartera",
    sit: "El directivo necesita pedir informes parciales para conocer el riesgo financiero global de la empresa.",
    obj: "Disponer de un cuadro de mando integral con KPIs de rentabilidad y riesgo de todos los activos en tiempo real." },
  { code: "04_2", dim: "D", name: "Sincronización de OKRs — técnica y negocio",
    sit: "Un cambio de material en obra tarda semanas en reflejarse en el análisis de rentabilidad de la oficina central.",
    obj: "Vincular el dato técnico del modelo con los objetivos de negocio para ver el impacto financiero de cada decisión al instante." },
];

export const QS: Question[] = [
  { dim: "A", retos: ["01_1", "01_2"],
    text: "En la fase de anteproyecto o viabilidad, ¿qué información económica y ambiental maneja el equipo técnico?",
    sub: "Sin juzgar si es suficiente — me interesa la realidad de cómo se trabaja hoy",
    opts: [
      { t: "Principalmente el coste de construcción. El impacto ambiental, si se calcula, llega después y por separado.", s: 100 },
      { t: "Tenemos ratios de coste por tipología y algún indicador de carbono, pero no los cruzamos en el mismo modelo.", s: 70 },
      { t: "Usamos herramientas de presupuesto y de huella de carbono, pero cada una vive en su propio sistema.", s: 30 },
      { t: "Trabajamos con un modelo que genera simultáneamente ratios económicas y ambientales desde el primer boceto.", s: 0 },
    ]},
  { dim: "A", retos: ["01_2", "02_3"],
    text: "Cuando hay que justificar el presupuesto de un proyecto ante dirección o ante un cliente, ¿qué argumento respalda las cifras?",
    sub: "Pienso en qué hay detrás del número — intuición experta, comparativa con históricos, modelo paramétrico…",
    opts: [
      { t: "La experiencia del técnico que lo elabora. Si él lo dice, se asume que es razonable.", s: 100 },
      { t: "Comparamos con proyectos anteriores, pero la búsqueda es manual y los datos no siempre son comparables.", s: 70 },
      { t: "Tenemos una base de ratios de proyectos anteriores, aunque no está conectada al modelo actual del proyecto.", s: 30 },
      { t: "El presupuesto se contrasta automáticamente con históricos de la misma tipología, fase y escala.", s: 0 },
    ]},
  { dim: "A", retos: ["01_3", "04_1"],
    text: "Piensa en el último proyecto donde hubo un sobrecoste relevante. ¿En qué momento se supo?",
    sub: "No hay respuesta incorrecta — es una pregunta sobre cuándo llega la información",
    opts: [
      { t: "Cuando ya estaba ejecutado o muy avanzado. La desviación se gestionó cuando no había mucho margen.", s: 100 },
      { t: "Relativamente tarde; alguien del equipo lo detectó revisando las certificaciones o el cierre mensual.", s: 70 },
      { t: "Con cierta antelación gracias al seguimiento del director de proyecto, aunque el proceso es manual.", s: 30 },
      { t: "Se detectó en fase de diseño gracias a un sistema de alertas antes de que afectara a la ejecución.", s: 0 },
    ]},
  { dim: "A", retos: ["01_4"],
    text: "¿Qué ocurre cuando un financiador o socio inversor pregunta por el cumplimiento de la Taxonomía Europea del proyecto?",
    sub: "Regulación ESG que condiciona el acceso a financiación verde — me interesa cómo está respondiendo hoy la organización",
    opts: [
      { t: "Es un tema pendiente. Sabemos que viene pero aún no tenemos un proceso para gestionarlo.", s: 100 },
      { t: "Lo gestiona un técnico o consultor externo recopilando datos manualmente del proyecto. Lleva tiempo.", s: 70 },
      { t: "Tenemos alguna herramienta o proceso, pero los indicadores no salen directamente del modelo del proyecto.", s: 30 },
      { t: "Los indicadores DNSH y ratios financieras exigidas se generan desde el propio modelo del proyecto.", s: 0 },
    ]},
  { dim: "B", retos: ["02_1"],
    text: "Imagina que mañana tu técnico con más años en la empresa decide irse. ¿Qué se va con él?",
    sub: "No pienso solo en documentos — pienso en criterios, ratios que solo él sabe, decisiones que tomó y por qué",
    opts: [
      { t: "Se va gran parte del criterio técnico real. Hay documentos, pero no capturan el razonamiento detrás.", s: 100 },
      { t: "Se va más de lo que quisiéramos. Hay carpetas y correos, pero reconstruir su lógica lleva semanas.", s: 70 },
      { t: "Tenemos algo documentado, pero la base no está estructurada de forma que sea fácilmente reutilizable.", s: 30 },
      { t: "El conocimiento está en el modelo de la organización. Su marcha sería una pérdida, no una descapitalización.", s: 0 },
    ]},
  { dim: "B", retos: ["02_2"],
    text: "Cuando llega un pliego de licitación de 300 páginas, ¿cuánto tarda el equipo en tener una lectura técnica útil?",
    sub: "Me interesa la velocidad real, no la ideal — y si hay riesgo de que algo importante pase desapercibido",
    opts: [
      { t: "Días. Cada técnico lee lo que le toca y se pone en común. Hay riesgo de que algo se escape.", s: 100 },
      { t: "Tenemos un esquema de análisis propio que ayuda, pero sigue siendo un proceso manual intensivo.", s: 70 },
      { t: "Usamos alguna herramienta de IA para extraer puntos clave, aunque no está integrada con nuestros proyectos.", s: 30 },
      { t: "Un asistente procesa el pliego en minutos, extrae los requisitos clave y los cruza con proyectos similares.", s: 0 },
    ]},
  { dim: "B", retos: ["02_3", "01_2"],
    text: "Al arrancar el estudio económico de un proyecto nuevo, ¿cómo influyen los proyectos ya entregados?",
    sub: "Pienso en si los costes reales de obras terminadas alimentan automáticamente las estimaciones futuras",
    opts: [
      { t: "Poco o nada de forma sistemática. Cada proyecto nuevo arranca sin aprender formalmente del anterior.", s: 100 },
      { t: "Alguien del equipo recuerda proyectos similares y ajusta a ojo. Depende de quién haga el estudio.", s: 70 },
      { t: "Tenemos una base de datos de costes reales, pero consultarla y aplicarla al nuevo proyecto es manual.", s: 30 },
      { t: "Los costes reales de proyectos cerrados actualizan automáticamente las bases de referencia para los siguientes.", s: 0 },
    ]},
  { dim: "C", retos: ["03_1"],
    text: "A mitad de un proyecto complejo, ¿cuántas 'versiones del proyecto' coexisten entre los distintos agentes?",
    sub: "Promotor, arquitecto, constructora, técnico de costes — pienso en si trabajan sobre el mismo modelo o sobre versiones distintas",
    opts: [
      { t: "Varias, con diferencias que se descubren tarde. Los conflictos de versiones son una fuente habitual de retrabajo.", s: 100 },
      { t: "Intentamos mantener una referencia común, pero la coordinación es por correo y reuniones; hay desfases.", s: 70 },
      { t: "Compartimos un repositorio (BIM o similar), pero los cambios no siempre se trazan ni se comunican bien.", s: 30 },
      { t: "Todos trabajan sobre el mismo modelo con trazabilidad de cambios. Los conflictos de versión no existen.", s: 0 },
    ]},
  { dim: "C", retos: ["03_2"],
    text: "Si asignas a un equipo distinto un proyecto del mismo tipo que ya has entregado bien, ¿qué nivel de resultado esperas?",
    sub: "Me interesa si la calidad del proceso depende del equipo o si está en el sistema",
    opts: [
      { t: "Honestamente, el resultado varía bastante. Hay equipos que funcionan mejor que otros con el mismo tipo de proyecto.", s: 100 },
      { t: "Hay procedimientos escritos, pero en la práctica cada equipo los adapta. El resultado es desigual.", s: 70 },
      { t: "Los procesos están bastante definidos, aunque su seguimiento y actualización requieren esfuerzo manual.", s: 30 },
      { t: "El resultado debería ser equivalente. Trabajamos con procedimientos estándar que el equipo aplica sin ambigüedad.", s: 0 },
    ]},
  { dim: "C", retos: ["03_3"],
    text: "Si dentro de dos años alguien cuestiona judicialmente una decisión técnica tomada hoy, ¿qué prueba existe de quién la tomó, con qué información y por qué?",
    sub: "Pienso en la seguridad jurídica real — no en lo que deberíamos tener, sino en lo que hay",
    opts: [
      { t: "Correos y actas dispersas. Reconstruir la trazabilidad completa llevaría días y probablemente quedaría incompleta.", s: 100 },
      { t: "Hay documentación, pero no está centralizada ni organizada para ser fácilmente auditable.", s: 70 },
      { t: "Tenemos un sistema de registro de decisiones, aunque no está completamente integrado con el modelo del proyecto.", s: 30 },
      { t: "Existe un historial estructurado e inalterable con la decisión, el responsable, la fecha y el contexto técnico.", s: 0 },
    ]},
  { dim: "D", retos: ["04_1", "01_3"],
    text: "Si esta tarde dirección te pregunta cuál es el riesgo financiero real de la cartera de proyectos en curso, ¿en cuánto tiempo tienes una respuesta fiable?",
    sub: "No la respuesta que darías — el tiempo real que necesitarías para preparar algo en lo que confiar",
    opts: [
      { t: "Días. Necesitaría pedir datos a cada equipo, consolidar en Excel y revisar que no hay errores.", s: 100 },
      { t: "Algunas horas. Tengo dashboards parciales pero necesito completar huecos manualmente.", s: 70 },
      { t: "Tengo visibilidad por proyecto, pero la vista consolidada de cartera requiere trabajo adicional.", s: 30 },
      { t: "Menos de una hora. El cuadro de mando muestra el estado en tiempo real sin trabajo adicional.", s: 0 },
    ]},
  { dim: "D", retos: ["04_2", "01_3"],
    text: "Un arquitecto propone cambiar el sistema de fachada de un edificio en fase de proyecto básico. ¿Cuándo sabe el promotor si eso mejora o empeora la rentabilidad del activo?",
    sub: "Pienso en el tiempo real entre la decisión técnica y su reflejo en el análisis económico",
    opts: [
      { t: "Semanas o más. El equipo técnico y el financiero trabajan en ciclos distintos y no están sincronizados.", s: 100 },
      { t: "Días. Alguien tiene que recalcular el presupuesto y pasarlo al modelo financiero manualmente.", s: 70 },
      { t: "Horas. Hay cierta integración, pero el proceso de actualización no es completamente automático.", s: 30 },
      { t: "De forma inmediata. El cambio en el modelo técnico actualiza automáticamente los indicadores financieros.", s: 0 },
    ]},
];

export const PROFILE_QUESTIONS: Record<ProfileKey, string[]> = {
  promotor_inversor: [
    "En los proyectos que promueves, ¿qué información económica y ambiental recibes del equipo técnico en la fase de viabilidad — y en qué momento la recibes?",
    "Cuando recibes el presupuesto de un proyecto nuevo, ¿qué argumento te convence de que la cifra es fiable — y cuándo te has encontrado con que no lo era?",
    "En los proyectos que has promovido, ¿en qué momento te has enterado de que había un sobrecoste relevante — y cuánto margen de reacción tenías cuando llegó la noticia?",
    "Cuando un financiador o socio te pregunta por el cumplimiento de la Taxonomía Europea, ¿qué puedes responder con datos propios del proyecto — y cuánto te cuesta preparar esa respuesta?",
    "Si el director técnico o el gestor de proyecto con más años en los proyectos que promueves decidiera irse, ¿qué conocimiento crítico sobre esos activos se iría con él?",
    "Cuando recibes documentación técnica o normativa extensa de un proyecto — pliegos, informes de due diligence, normativa aplicable — ¿cuánto tiempo necesitas para tener una lectura fiable de los puntos críticos?",
    "¿Cómo se usan los costes reales de las obras que has promovido para mejorar los presupuestos de los proyectos siguientes — o esa información se pierde al cerrar el proyecto?",
    "En los proyectos que promueves, ¿con cuántas versiones distintas del proyecto trabajan simultáneamente los distintos agentes — y cómo te enteras cuando hay diferencias relevantes entre ellas?",
    "Si asignas el mismo tipo de proyecto a dos equipos técnicos distintos, ¿esperas un resultado equivalente — o sabes que el resultado depende de quién esté en el equipo?",
    "Si dentro de dos años alguien cuestionara una decisión técnica tomada en uno de tus proyectos hoy, ¿qué prueba existe de quién la tomó, con qué información y por qué?",
    "Si esta tarde alguien te preguntara cuál es el riesgo financiero real de todos tus proyectos en curso, ¿en cuánto tiempo tendrías una respuesta en la que confiar?",
    "Cuando el equipo técnico propone un cambio relevante en un proyecto tuyo — sistema constructivo, programa, superficie — ¿en cuánto tiempo sabes si eso mejora o empeora la rentabilidad del activo?",
  ],
  direccion: [
    "En la fase de anteproyecto, ¿qué información económica y ambiental manejan los equipos técnicos de tu organización, y cómo llega esa información a dirección?",
    "Cuando la dirección aprueba el presupuesto de un proyecto, ¿sobre qué base técnica se toma esa decisión?",
    "Piensa en un sobrecoste relevante en los últimos proyectos de la organización. ¿En qué momento llegó la información a dirección, y qué capacidad de actuación había en ese punto?",
    "¿Cómo responde actualmente la organización cuando se exige acreditar el cumplimiento de la Taxonomía Europea ante financiadores o en procesos de due diligence?",
    "Si mañana el técnico con más conocimiento acumulado sobre los proyectos en curso dejara la organización, ¿qué capacidad técnica y qué criterio se perdería con él?",
    "Cuando llega documentación técnica compleja que afecta a decisiones estratégicas — normativa, informes técnicos, condicionantes de financiación — ¿cómo llega esa lectura a la dirección, y en qué plazo?",
    "¿Cómo fluye el aprendizaje económico entre proyectos en la organización — y qué mecanismo existe para que los costes reales de una obra mejoren las estimaciones de la siguiente?",
    "En los proyectos en curso de la organización, ¿cuántas versiones distintas del mismo proyecto coexisten entre los diferentes equipos — y cómo se resuelven los conflictos cuando aparecen?",
    "¿En qué medida el nivel de calidad de los proyectos de la organización depende de los procedimientos del sistema frente a las capacidades individuales de los equipos asignados?",
    "Si la organización tuviera que demostrar ante un tribunal o una auditoría qué decisiones técnicas se tomaron en un proyecto y con qué criterio, ¿qué documentación existe y qué tiempo llevaría reconstruirla?",
    "Si el consejo o un socio inversor pidiera esta tarde una lectura del riesgo financiero consolidado de la cartera de proyectos, ¿en cuánto tiempo podría dirección dar una respuesta fiable?",
    "Cuando un equipo técnico propone un cambio relevante en un proyecto en curso, ¿en cuánto tiempo llega el impacto económico de ese cambio al análisis de dirección?",
  ],
  estudios_constructor: [
    "Al arrancar un estudio, ¿qué información económica y ambiental tienes disponible sobre el proyecto antes de cerrar el presupuesto de oferta?",
    "Cuando presentas el presupuesto de una oferta, ¿qué puedes demostrar al cliente sobre la fiabilidad de las cifras?",
    "En las obras que has estudiado y cuyo resultado de ejecución conoces, ¿cuándo se detectaron las desviaciones más importantes respecto al presupuesto de oferta?",
    "¿Cómo se integran los criterios de Taxonomía Europea en la elaboración de la oferta técnica y económica — o es algo que se gestiona fuera del proceso de estudio?",
    "Si el técnico que mejor conoce las bases de costes y los criterios de las últimas ofertas dejara el equipo de estudios, ¿qué se iría con él — y cuánto tardaría en recuperarse ese nivel?",
    "Cuando llega un pliego de licitación extenso, ¿cuánto tiempo tarda el equipo en tener una lectura técnica útil — y qué riesgo hay de que algo importante pase desapercibido?",
    "¿Cómo influyen los costes reales de las obras ejecutadas en la elaboración de los presupuestos de nuevas ofertas — y cuánto de ese aprendizaje es sistemático frente a cuánto es informal?",
    "Durante la fase de estudio y elaboración de la oferta, ¿sobre qué versión del proyecto trabajáis — y cómo os coordinais con el equipo de diseño cuando hay cambios relevantes?",
    "Si el equipo de estudios que elaboró vuestra mejor oferta reciente fuera reemplazado por otro equipo de la misma organización, ¿esperarías un resultado comparable?",
    "Si el cliente cuestionara una decisión técnica o económica tomada durante la elaboración de la oferta, ¿qué registro existe de quién la tomó, con qué información y por qué?",
    "Si la dirección pidiera esta tarde el estado económico actualizado de todos los estudios y ofertas en curso, ¿en cuánto tiempo podría el equipo proporcionar una respuesta fiable?",
    "Cuando durante el estudio se plantea una alternativa técnica — sistema constructivo distinto, variación de programa — ¿cuánto tiempo tarda el equipo en saber si eso mejora o empeora el margen de la oferta?",
  ],
  arquitecto_ingeniero: [
    "En fase de anteproyecto, ¿con qué información económica y ambiental trabajas mientras tomas decisiones de diseño?",
    "Cuando justificas el presupuesto estimado de un proyecto ante el promotor o la dirección, ¿qué respaldas con datos objetivos y qué queda en criterio propio?",
    "En proyectos que has diseñado y que luego se han ejecutado, ¿en qué momento se detectaron las desviaciones de coste más importantes — y en qué fase se originaron?",
    "¿Cómo se incorporan los criterios de Taxonomía Europea en las decisiones de diseño — y qué datos del proyecto permiten acreditar ese cumplimiento?",
    "Si el arquitecto o ingeniero que lleva más tiempo trabajando en un proyecto saliera del equipo, ¿qué criterio de diseño y qué historial de decisiones se perdería con él?",
    "Cuando recibes normativa técnica, condicionantes urbanísticos o documentación de referencia extensa, ¿cuánto tiempo necesitas para integrar esa información en las decisiones de diseño?",
    "¿Cómo se incorporan los datos de coste real de proyectos ejecutados al proceso de estimación de nuevos diseños — y en qué medida ese aprendizaje es automático o depende de que alguien lo busque?",
    "Durante el desarrollo del diseño, ¿cuántas versiones distintas del proyecto circulan entre los agentes — y cómo garantizas que los cambios que introduces llegan correctamente a todos?",
    "Si otro arquitecto o ingeniero de tu organización tomara un proyecto tuyo en la misma fase, ¿podría continuarlo con la misma calidad técnica — o perdería criterio y contexto que no está documentado?",
    "Si alguien cuestionara una decisión de diseño tomada durante el proyecto, ¿qué documentación existe de por qué se tomó esa decisión, qué alternativas se consideraron y quién la aprobó?",
    "Si el cliente o la dirección pidiera esta tarde una estimación actualizada del estado económico de todos los proyectos en desarrollo, ¿en cuánto tiempo podrías dar una respuesta en la que confiar?",
    "Cuando tomas una decisión de diseño relevante — cambio de sistema constructivo, ajuste de programa, variación de materiales — ¿en cuánto tiempo puedes saber su impacto en el coste y la viabilidad del proyecto?",
  ],
  delegado_pm: [
    "Al recibir el proyecto para ejecución, ¿qué información económica y ambiental te llega del equipo de diseño — y en qué estado llega?",
    "Cuando recibes el presupuesto de ejecución, ¿tienes acceso a los datos que lo respaldan o solo al número final?",
    "Piensa en el último sobrecoste relevante en una obra a tu cargo. ¿Cuándo se supo, qué información lo reveló y cuánto margen había para corregirlo?",
    "¿Cómo se gestionan en obra los requisitos de Taxonomía Europea y ESG — y qué información del proyecto necesitas para poder justificar el cumplimiento?",
    "Si el jefe de obra o el técnico de mayor experiencia en una obra a tu cargo decidiera irse, ¿qué conocimiento operativo se perdería — y cómo afectaría a la continuidad de la ejecución?",
    "Cuando recibes planos, especificaciones técnicas o documentación de proyecto de gran volumen, ¿cuánto tarda el equipo en tener una lectura operativa útil para planificar la ejecución?",
    "¿Cómo se comparten los datos de coste real de la obra con el equipo de estudios para mejorar futuras ofertas — y con qué regularidad ocurre ese intercambio?",
    "En obra, ¿con cuántas versiones distintas del proyecto trabajáis simultáneamente — y cómo os enteráis cuando hay cambios en el proyecto que afectan a lo que ya está ejecutado o en marcha?",
    "Si cambiaras el equipo de una obra en plena ejecución, ¿el nuevo equipo podría continuar con el mismo nivel de control y calidad — o habría una pérdida de criterio operativo con el cambio?",
    "Si en obra surgiera un conflicto sobre una decisión técnica tomada semanas antes — un cambio, una aprobación, una instrucción — ¿qué registro existe de quién la tomó, cuándo y en qué contexto?",
    "Si la dirección pidiera esta tarde el estado económico real de todas las obras a tu cargo — costes comprometidos, desvíos acumulados, previsión de cierre — ¿en cuánto tiempo podrías dar una respuesta fiable?",
    "Cuando se produce un cambio técnico en obra — modificación de partida, alternativa constructiva, cambio de material — ¿en cuánto tiempo se conoce su impacto en el presupuesto de ejecución y en el cierre previsto?",
  ],
  otro: [
    "En las actuaciones sobre el activo, ¿qué información económica y ambiental manejas antes de decidir qué intervención hacer?",
    "Cuando propones una actuación de rehabilitación o mejora, ¿con qué comparas el presupuesto para saber si es razonable?",
    "En las intervenciones sobre activos a tu cargo, ¿cuándo suelen detectarse las desviaciones de coste respecto a lo presupuestado?",
    "¿Cómo se acredita el cumplimiento de la Taxonomía Europea en las actuaciones sobre el activo — y qué datos del activo están disponibles para hacerlo?",
    "Si el técnico que gestiona un activo con más continuidad dejara el equipo, ¿qué conocimiento sobre el estado y el historial del activo se perdería con él?",
    "Cuando recibes contratos de mantenimiento, normativa técnica del activo o informes de inspección extensos, ¿cuánto tarda el equipo en extraer los puntos operativos clave?",
    "¿Cómo se usan los datos de coste real de las intervenciones pasadas sobre el activo para presupuestar las siguientes — o cada actuación se estudia sin referencia a las anteriores?",
    "En la gestión del activo, ¿cuántas versiones de la documentación técnica coexisten entre los distintos sistemas y agentes — y cómo se mantiene actualizada la información de referencia?",
    "Si el equipo que gestiona un activo fuera reemplazado, ¿el nuevo equipo podría mantener el mismo nivel de calidad operativa — o perdería contexto que no está documentado en ningún sistema?",
    "Si surgiera un litigio sobre una actuación técnica realizada en el activo, ¿qué documentación existe de quién tomó la decisión, con qué criterio y con qué información en ese momento?",
    "Si alguien te pidiera esta tarde el estado económico actualizado de todos los activos a tu cargo — coste de operación, desviaciones, previsión — ¿en cuánto tiempo tendrías una respuesta fiable?",
    "Cuando se decide una actuación de mejora o rehabilitación en un activo, ¿en cuánto tiempo puedes estimar su impacto en el coste de operación y en el valor del activo?",
  ],
};

export const PROFILE_META: Record<ProfileKey, ProfileMeta> = {
  promotor_inversor: {
    label: "Promotor / Inversor",
    weights: { A: 0.35, B: 0.15, C: 0.20, D: 0.30 },
    summary: "Tu lectura se centra en márgenes, TIR y riesgo de cartera. Los retos más costosos son los que impiden conocer el impacto real de cada decisión de diseño sobre la rentabilidad del activo antes de comprometer presupuesto.",
    priorities: ["A", "D", "C", "B"],
    retoContext: {
      "01_1": "Sin ratios integradas desde el inicio, el presupuesto de viabilidad se apoya en estimaciones parciales. El coste real se conoce demasiado tarde para ajustar el producto.",
      "01_2": "Cada proyecto que arranca sin mirar al histórico es una inversión sin red. Los datos de tus proyectos anteriores son el activo más valioso que tienes — y casi nadie lo usa.",
      "01_3": "Los sobrecostes en edificación raramente son sorpresas. Son señales que nadie leyó a tiempo. Un sistema preventivo los detecta en diseño, no en obra.",
      "01_4": "La financiación verde ya está condicionada a acreditar el cumplimiento de Taxonomía EU. Sin un proceso automatizado, el coste de certificación lastra la viabilidad de cada operación.",
      "02_1": "Cuando el criterio técnico vive en personas, la empresa no escala. La cartera crece, pero la capacidad de decisión no.",
      "02_2": "El tiempo de análisis de una licitación o un due diligence técnico es tiempo de riesgo. Reducirlo es mejorar la posición competitiva.",
      "02_3": "Un promotor que no aprende sistemáticamente de sus obras anteriores repite los mismos márgenes de error en cada nueva inversión.",
      "03_1": "Cuando promotor, arquitecto y constructora trabajan sobre documentación distinta, los conflictos de versión se resuelven en obra — y eso cuesta dinero.",
      "03_2": "La calidad del proceso no puede depender de quién esté en el proyecto. La escalabilidad de la cartera requiere que el estándar sea del sistema, no del equipo.",
      "03_3": "La responsabilidad técnica en edificación tiene consecuencias legales y económicas. La trazabilidad de decisiones no es burocracia — es blindaje.",
      "04_1": "Gestionar una cartera sin visibilidad consolidada en tiempo real es gestionar con retraso. Las decisiones de inversión necesitan datos actuales, no informes de la semana pasada.",
      "04_2": "El promotor necesita saber hoy si el cambio que propone el arquitecto mejora o empeora la TIR. No dentro de dos semanas cuando ya está en el presupuesto de ejecución.",
    },
  },
  direccion: {
    label: "CEO / CIO / COO",
    weights: { A: 0.30, B: 0.20, C: 0.20, D: 0.30 },
    summary: "Tu lectura combina gobernanza, escalabilidad y control operativo. Los retos más críticos son los que hacen que la organización dependa de personas concretas en lugar de operar sobre sistemas y procesos reproducibles.",
    priorities: ["A", "D", "B", "C"],
    retoContext: {
      "01_1": "Una organización que no cruza coste y sostenibilidad desde el inicio toma decisiones de producto parcialmente ciegas. El impacto ambiental ya es un factor de valor del activo.",
      "01_2": "Sin mirar al histórico de forma sistemática, la dirección aprueba presupuestos sin saber si son competitivos o simplemente razonables. Es un riesgo estructural.",
      "01_3": "La cultura reactiva ante desvíos es cara. No solo en costes directos — también en reputación, en relaciones con clientes y en margen de maniobra.",
      "01_4": "La Taxonomía EU es regulación, no tendencia. Las organizaciones que no tengan procesos automatizados en los próximos años pagarán un coste operativo que sus competidores no tendrán.",
      "02_1": "El conocimiento técnico que no está en el sistema de la organización es un riesgo de negocio. Cada jubilación o salida de un técnico clave debería ser gestionable, no traumática.",
      "02_2": "La velocidad de análisis técnico es una ventaja competitiva en licitaciones y en toma de decisiones de inversión. Las organizaciones que analizan más rápido ganan más oportunidades.",
      "02_3": "Las organizaciones que no cierran el ciclo entre lo planificado y lo real están condenadas a repetir los mismos errores de estimación. El aprendizaje sistemático es la diferencia entre crecer y simplemente facturar más.",
      "03_1": "Los silos entre agentes son la principal fuente de retrabajo en edificación. Eliminarlos no es una cuestión de herramientas — es una decisión de gobernanza.",
      "03_2": "La estandarización operativa es lo que permite crecer sin perder calidad. Sin ella, cada nuevo proyecto es un experimento.",
      "03_3": "La exposición legal de una organización de edificación sin trazabilidad de decisiones técnicas es mayor de lo que parece hasta que hay un siniestro.",
      "04_1": "La dirección que gestiona por informes siempre va con retraso. La visibilidad en tiempo real no es un lujo — es la condición para tomar decisiones oportunas.",
      "04_2": "Cuando la técnica y el negocio no están sincronizados, la dirección toma decisiones de inversión con información incompleta. El coste de esa brecha se acumula en cada proyecto.",
    },
  },
  estudios_constructor: {
    label: "Director de Estudios",
    weights: { A: 0.30, B: 0.25, C: 0.30, D: 0.15 },
    summary: "Tu lectura se centra en la precisión de la oferta, la velocidad de respuesta ante licitaciones y la consistencia entre lo que se presupuesta y lo que luego se ejecuta. Los retos más costosos son los que generan desviaciones entre oferta y obra.",
    priorities: ["B", "C", "A", "D"],
    retoContext: {
      "01_1": "Un estudio económico que no integra ratios de sostenibilidad desde el inicio puede perder licitaciones que ya exigen criterios ESG, o llevar a obra compromisos que no podrán cumplirse.",
      "01_2": "La fiabilidad del presupuesto de oferta depende directamente de qué tan bien se usan los datos de proyectos ejecutados. Sin esa base, el margen es una estimación con incertidumbre no cuantificada.",
      "01_3": "Los desvíos que se detectan en obra ya son costes asumidos. Los que se detectan en el estudio aún son oportunidades de corrección.",
      "01_4": "Las licitaciones con requisitos de Taxonomía EU son ya una realidad y serán más frecuentes. La capacidad de responder con datos técnicos verificables es una ventaja competitiva directa.",
      "02_1": "Cuando el know-how de las mejores ofertas está en la cabeza de dos o tres técnicos, la capacidad de respuesta ante múltiples licitaciones simultáneas queda limitada por esas personas.",
      "02_2": "El análisis de un pliego de 300 páginas en horas en lugar de días no es solo eficiencia — es la diferencia entre poder o no concurrir a una licitación con el margen ajustado.",
      "02_3": "Cada obra entregada es una base de datos de lecciones aprendidas. Si no se captura de forma sistemática, la siguiente oferta parte del mismo nivel de incertidumbre.",
      "03_1": "Las diferencias entre el modelo del estudio y el de la dirección facultativa son la semilla de los conflictos de obra. Unificar la base desde el inicio los elimina.",
      "03_2": "Un proceso de elaboración de estudios que varía según el técnico asignado produce ofertas con niveles de riesgo distintos. La estandarización no recorta criterio — protege el margen.",
      "03_3": "En un litigio sobre responsabilidad por desviación de coste, la trazabilidad de las decisiones del estudio es la primera línea de defensa.",
      "04_1": "La visibilidad del estado de los estudios en curso permite a la dirección priorizar recursos y detectar los que tienen más riesgo antes de presentar la oferta.",
      "04_2": "Saber el impacto en margen de cada alternativa técnica durante el estudio es lo que permite optimizar la oferta — no ajustar precio, sino mejorar la propuesta.",
    },
  },
  arquitecto_ingeniero: {
    label: "Arquitecto / Ingeniero",
    weights: { A: 0.35, B: 0.15, C: 0.25, D: 0.25 },
    summary: "Tu lectura se centra en la calidad técnica del diseño, la coordinación con otros agentes y la trazabilidad de las decisiones que tomas a lo largo del proyecto. Los retos más relevantes son los que generan retrabajo o pérdida de criterio técnico entre fases.",
    priorities: ["B", "C", "D", "A"],
    retoContext: {
      "01_1": "Un diseño que no conoce su impacto en coste y sostenibilidad hasta fases avanzadas genera decisiones que luego hay que deshacer. La integración de ratios desde el boceto reduce ese retrabajo.",
      "01_2": "Los datos de proyectos similares son la referencia más honesta para validar si un diseño es viable. Sin esa base, la validación depende del criterio individual del técnico.",
      "01_3": "Los cambios de diseño que generan desvíos de coste suelen ser rastreables a decisiones que, con más información, habrían sido distintas. Ver el impacto en tiempo real cambia la forma de diseñar.",
      "01_4": "El diseño es la fase donde se determina si un edificio va a cumplir la Taxonomía EU. Integrar esos criterios desde el inicio evita tener que rediseñar elementos para cumplir la normativa.",
      "02_1": "El criterio técnico que un arquitecto o ingeniero acumula a lo largo de su carrera es el activo más valioso de un estudio. Sin un sistema que lo capture, se pierde con cada persona que se va.",
      "02_2": "Analizar normativa, jurisprudencia técnica y referencias de proyectos similares consume horas de trabajo que podrían dedicarse a diseñar. La IA no sustituye el criterio — libera tiempo para ejercerlo.",
      "02_3": "Saber cuánto costó realmente construir lo que diseñaste es la mejor forma de mejorar la precisión de tus próximas propuestas. Ese feedback raramente llega de forma sistemática.",
      "03_1": "El conflicto entre la versión del proyecto que maneja el promotor y la que tiene el arquitecto es la fuente de la mayoría de las reclamaciones. Una única fuente de verdad los elimina.",
      "03_2": "Los procesos de proyecto que se repiten de la misma forma — independientemente de quién los ejecute — son los que permiten crecer sin perder calidad técnica.",
      "03_3": "La responsabilidad civil del proyectista requiere poder demostrar qué información tenías cuando tomaste cada decisión de diseño. La trazabilidad no es burocracia — es protección profesional.",
      "04_1": "La visibilidad del estado económico del conjunto de proyectos en curso permite al estudio equilibrar carga de trabajo y detectar los que necesitan atención antes de que el problema escale.",
      "04_2": "Cuando un cliente pregunta qué pasa con la rentabilidad si cambia el sistema constructivo, poder responder en el momento —con datos, no con estimaciones— cambia la posición del arquitecto en la conversación.",
    },
  },
  delegado_pm: {
    label: "Delegado de construcción / PM",
    weights: { A: 0.20, B: 0.20, C: 0.30, D: 0.30 },
    summary: "Tu lectura se centra en la ejecución, el control de plazo y coste en obra, y la coordinación entre los agentes que intervienen en la construcción. Los retos más costosos son los que generan retrabajo, conflictos de información o desvíos que llegan tarde.",
    priorities: ["C", "D", "A", "B"],
    retoContext: {
      "01_1": "Llegar a obra sin ratios de coste y sostenibilidad bien definidas desde el proyecto básico significa que las optimizaciones posibles se hacen tarde, cuando el margen de maniobra ya es limitado.",
      "01_2": "Los datos de obras ejecutadas similares son la referencia más fiable para planificar. Sin esa base, la planificación parte de estimaciones con un margen de error que se paga en obra.",
      "01_3": "En obra, los desvíos que no se detectan en las dos primeras semanas se vuelven estructurales. Un sistema de alertas tempranas vinculado al modelo del proyecto los hace visibles antes.",
      "01_4": "Las obras con requisitos ESG necesitan datos técnicos verificables durante la ejecución. Sin un proceso integrado, ese seguimiento se convierte en carga administrativa para el equipo de obra.",
      "02_1": "Cuando el delegado o el jefe de obra que conoce todos los detalles de un proyecto se va a otra obra, la continuidad del conocimiento depende de lo que haya documentado. Que suele ser poco.",
      "02_2": "El análisis de planos, especificaciones y normativa en obra consume tiempo de perfiles técnicos que deberían estar resolviendo problemas de ejecución, no leyendo documentos.",
      "02_3": "Las obras que no cierran el ciclo entre planificado y real son las que repiten los mismos problemas de productividad y desvío. El aprendizaje sistemático empieza por capturar lo que pasó realmente.",
      "03_1": "Los conflictos de versión entre el proyecto que tiene el arquitecto, el que tiene la constructora y el que tiene el promotor son una fuente cotidiana de retrabajo y de conflictos de responsabilidad.",
      "03_2": "Un proceso de obra que funciona bien cuando está un delegado concreto pero no cuando está otro no es un proceso — es la habilidad de una persona. La estandarización lo hace reproducible.",
      "03_3": "En un siniestro o en un litigio por defectos constructivos, la primera pregunta es quién sabía qué y cuándo. Sin trazabilidad, esa respuesta se construye a posteriori y suele ser incompleta.",
      "04_1": "La dirección que no tiene visibilidad del estado real de las obras en curso toma decisiones de asignación de recursos con información tardía. El coste de esa opacidad se distribuye en todas las obras.",
      "04_2": "Cuando se decide en obra cambiar un elemento constructivo, el PM necesita saber en el momento si eso tiene implicaciones en el presupuesto total y en los compromisos con el promotor.",
    },
  },
  otro: {
    label: "Gestor / Propiedad / Facilities",
    weights: { A: 0.30, B: 0.25, C: 0.15, D: 0.30 },
    summary: "Tu lectura se centra en el ciclo completo del activo — desde la adquisición hasta la operación. Los retos más relevantes son los que impiden conocer el estado real del activo, anticipar costes de mantenimiento o tomar decisiones de inversión con datos fiables.",
    priorities: ["A", "B", "C", "D"],
    retoContext: {
      "01_1": "Sin ratios integradas de coste y sostenibilidad del activo, las decisiones de rehabilitación o mejora se toman con visibilidad parcial sobre su impacto en el valor y en los compromisos ESG.",
      "01_2": "Los datos de actuaciones anteriores sobre activos similares son la referencia más honesta para presupuestar intervenciones futuras. Sin esa base, cada actuación parte desde cero.",
      "01_3": "En la gestión de activos, los desvíos de coste en mantenimiento o rehabilitación que no se detectan a tiempo se convierten en deterioro del margen operativo del activo.",
      "01_4": "Los activos que no pueden acreditar su cumplimiento con la Taxonomía EU tienen cada vez más dificultades para acceder a financiación favorable o para cumplir compromisos de sostenibilidad corporativa.",
      "02_1": "El conocimiento sobre el estado real de un activo — qué se hizo, cuándo, por qué y con qué resultado — raramente está estructurado de forma que sea útil para el equipo que llega después.",
      "02_2": "El análisis de contratos de mantenimiento, normativa técnica y datos del activo consume tiempo de gestión que podría reducirse significativamente con herramientas de IA bien integradas.",
      "02_3": "La comparación sistemática entre el coste previsto y el real de las actuaciones sobre un activo es la base para mejorar la planificación presupuestaria a largo plazo.",
      "03_1": "Cuando el gestor del activo, la propiedad y los proveedores de servicios trabajan sobre información distinta, los problemas de coordinación se resuelven tarde y a mayor coste.",
      "03_2": "Los procesos de operación y mantenimiento que dependen de personas concretas son frágiles. La estandarización los hace robustos ante cambios de equipo o de proveedor.",
      "03_3": "La trazabilidad de las intervenciones técnicas sobre un activo es fundamental tanto para gestionar garantías como para documentar el historial ante una venta o una due diligence.",
      "04_1": "Gestionar una cartera de activos sin visibilidad consolidada en tiempo real significa gestionar con retraso. Las decisiones de inversión o desinversión necesitan datos actuales.",
      "04_2": "Cuando una decisión técnica sobre un activo — cambio de sistema, intervención de mejora — no se refleja rápidamente en el análisis de rentabilidad, se pierde la capacidad de optimizar el retorno.",
    },
  },
};

export const GOOD_ANSWER_LABELS: Record<number, string> = {
  0:  "Calculáis ratios económicas y ambientales de forma integrada desde el inicio del proyecto",
  1:  "Usáis vuestro histórico de proyectos para validar nuevos presupuestos",
  2:  "El control de desvíos es proactivo y no depende solo de la experiencia individual",
  3:  "Tenéis un proceso para gestionar los indicadores de Taxonomía Europea",
  4:  "El conocimiento técnico de la organización está estructurado y no depende solo de personas clave",
  5:  "Disponéis de herramientas de análisis documental que reducen el tiempo de análisis de pliegos",
  6:  "Los costes reales de proyectos anteriores alimentan las estimaciones de los nuevos",
  7:  "Los agentes del proyecto trabajan sobre una base de información compartida",
  8:  "Los procesos de proyecto están estandarizados de forma que el resultado no depende del equipo",
  9:  "Las decisiones técnicas quedan registradas con trazabilidad y responsable",
  10: "La dirección tiene visibilidad del estado de rentabilidad de la cartera sin depender de informes manuales",
  11: "Los cambios técnicos se reflejan de forma ágil en el análisis de rentabilidad",
};

