export const SITE_ASSETS = {
  branding: {
    kitDigitalLogo: "/images/branding/kit-digital-logo.png",
  },
  home: {
    heroBackgroundGif: "/images/home/yutopias-hero-background.gif",
    partnersCtaLounge: "/images/home/partners-cta-lounge.jpg",
    earlyAdopterLogos: [
      "/images/home/early-adopters/logos/cbre-group.png",
      "/images/home/early-adopters/logos/construcia.png",
      "/images/home/early-adopters/logos/infraestructures.png",
      "/images/home/early-adopters/logos/picharchitects.png",
      "/images/home/early-adopters/logos/serom.png",
      "/images/home/early-adopters/logos/serveo.png",
      "/images/home/early-adopters/logos/sorigue-logo.png",
    ] as const,
  },
  simulab: {
    dashboardMockup: "/images/simulab/simulab-yutopias-1.png",
  },
  challenge: {
    taxonomyPillars: "https://www.figma.com/api/mcp/asset/375736b8-0eff-4fb3-b643-4b8a37d765ab",
    rectangle1: "https://www.figma.com/api/mcp/asset/f173e924-0e8d-41af-8dfc-bf4978cd8413",
    rectangle64: "https://www.figma.com/api/mcp/asset/ee3fd680-947d-42b1-980c-8102635b2fbe",
    scanSearchIcon: "https://www.figma.com/api/mcp/asset/3e15a41a-8879-46dc-ab27-17faba9e3dca",
  },
  solution: {
    heroBackground: "https://www.figma.com/api/mcp/asset/3e389945-6b70-4968-84f5-0672aca32446",
    dashboardScreenshot: "https://www.figma.com/api/mcp/asset/aeaa2b0e-86ab-470f-b7db-e537d95aa4a8",
    simulabAgent: "https://www.figma.com/api/mcp/asset/a5011e1e-94c3-4721-b890-a47b6cb60a0c",
    cyclePlannerAgent: "https://www.figma.com/api/mcp/asset/e7445c60-61ec-4509-85ca-fbe64925fb57",
    platonAgent: "https://www.figma.com/api/mcp/asset/d639f810-0909-4ad2-b77c-94e1acc4764b",
    partnersBackground: "https://www.figma.com/api/mcp/asset/823d87c7-83a1-4599-a0bf-d7f1057b27dc",
    checkIcon: "/images/solution/check-icon.png",
    avatarPromotor: "https://www.figma.com/api/mcp/asset/23d6d3f7-56a6-4d2a-9363-36452898b874",
    avatarDirectorEstudios: "https://www.figma.com/api/mcp/asset/1903b11a-e162-4761-9fb9-c330e85022a0",
    avatarDelegadoConstruccion: "https://www.figma.com/api/mcp/asset/1ad89c3f-c18b-47fd-89fd-a61ac91f7ec5",
    avatarCeo: "https://www.figma.com/api/mcp/asset/e2476dce-65b6-4658-9d86-717f870b10fb",
    avatarArquitecto: "https://www.figma.com/api/mcp/asset/84d87ca9-3782-47b1-aa54-5fce0f7831c8",
    avatarGestor: "https://www.figma.com/api/mcp/asset/1d05a337-b28c-4cc5-b1a4-669438fd3fe6",
    platformBuilding: "/images/solution/platform-building.png",
  },
  programa: {
    hero: "/images/programa/hero.png",
    ecosystemRectSmall: "/images/programa/ecosystem/rect-small.png",
    ecosystemRectWide: "/images/programa/ecosystem/rect-wide.png",
    ecosystemLasalleRd: "/images/programa/ecosystem/lasalle-rd.png",
    ecosystemTechnova: "/images/programa/ecosystem/technova.png",
    ecosystemAccio: "/images/programa/ecosystem/accio.png",
    ecosystemGbce: "/images/programa/ecosystem/gbce.png",
    ecosystemItec: "/images/programa/ecosystem/itec.png",
    ecosystemDih4cat: "/images/programa/ecosystem/dih4cat.png",
    ecosystemIese: "/images/programa/ecosystem/iese.png",
    ecosystemBarcelonaContechHub: "/images/programa/ecosystem/barcelona-contech-hub.png",
    ecosystemSngular: "/images/programa/ecosystem/sngular.png",
    ecosystemGoogleForStartups: "/images/programa/ecosystem/google-for-startups.png",
  },
} as const;
