export const SITE_ASSETS = {
  branding: {
    kitDigitalLogo: "/images/branding/kit-digital-logo.png",
  },
  home: {
    heroBackgroundGif: "/images/home/yutopias-hero-background.gif",
    partnersCtaLounge: "/images/home/partners-cta-lounge.jpg",
    blogArticleCover: "/images/home/partners-cta-lounge.jpg",
    testimonialAvatar: "/images/home/testimonial-avatar.png",
    earlyAdopterLogos: [
      "/images/home/early-adopters/logos/cbre-group.png",
      "/images/home/early-adopters/logos/construcia.png",
      "/images/home/early-adopters/logos/infraestructures.png",
      "/images/home/early-adopters/logos/picharchitects.png",
      "/images/home/early-adopters/logos/serom.png",
      "/images/home/early-adopters/logos/serveo.png",
      "/images/home/early-adopters/logos/sorigue-logo.png",
    ] as const,
  },
  simulab: {
    dashboardMockup: "/images/simulab/simulab-yutopias-1.png",
  },
  challenge: {
    taxonomyPillars: "/images/challenge/taxonomy-pillars.webp",
    rectangle1: "/images/challenge/rectangle-1.webp",
    rectangle64: "/images/challenge/rectangle-64.webp",
    scanSearchIcon: "/images/challenge/scan-search-icon.svg",
  },
  solution: {
    heroBackground: "/images/solution/hero-background.webp",
    dashboardScreenshot: "/images/solution/dashboard-screenshot.webp",
    simulabAgent: "/images/solution/simulab-agent.webp",
    cyclePlannerAgent: "/images/solution/cycle-planner-agent.webp",
    platonAgent: "/images/solution/platon-agent.webp",
    partnersBackground: "/images/solution/partners-background.webp",
    checkIcon: "/images/solution/check-icon.png",
    avatarPromotor: "/images/solution/avatar-promotor.webp",
    avatarDirectorEstudios: "/images/solution/avatar-director-estudios.webp",
    avatarDelegadoConstruccion: "/images/solution/avatar-delegado-construccion.webp",
    avatarCeo: "/images/solution/avatar-ceo.webp",
    avatarArquitecto: "/images/solution/avatar-arquitecto.webp",
    avatarGestor: "/images/solution/avatar-gestor.webp",
    platformBuilding: "/images/solution/platform-building.png",
  },
  about: {
    heroBackgroundVideo: "/videos/about-hero-background.mp4",
    founderJuanjoMoreno: "/images/about/founders/juanjo-moreno.png",
    founderEduardoNunez: "/images/about/founders/eduardo-nunez.png",
    founderIvanPerez: "/images/about/founders/ivan-perez.png",
    teamEugeniaRossetti: "/images/about/team/eugenia-rossetti.png",
    teamAlejandroGlejberman: "/images/about/team/alejandro-glejberman.png",
    teamTereTrepat: "/images/about/team/tere-trepat.png",
    teamAidaFreixanet: "/images/about/team/aida-freixanet.png",
    teamLauraIglesias: "/images/about/team/laura-iglesias.png",
    teamAndresMontanez: "/images/about/team/andres-montanez.png",
    teamMiguelAngelZamora: "/images/about/team/miguel-angel-zamora.png",
    teamPedroGonzalezAnta: "/images/about/team/pedro-gonzalez-anta.png",
    teamMariCarmenSanchez: "/images/about/team/mari-carmen-sanchez.png",
    ecosystemEurecat: "/images/about/ecosystem/eurecat.png",
    ecosystemEoi: "/images/about/ecosystem/eoi.png",
    ecosystemEsade: "/images/about/ecosystem/esade.png",
  },
  programa: {
    hero: "/images/programa/hero.png",
    heroBackground: "/images/programa/hero-background.jpg",
    ecosystemRectSmall: "/images/programa/ecosystem/rect-small.png",
    ecosystemRectWide: "/images/programa/ecosystem/rect-wide.png",
    ecosystemLasalleRd: "/images/programa/ecosystem/lasalle-rd.png",
    ecosystemTechnova: "/images/programa/ecosystem/technova.png",
    ecosystemAccio: "/images/programa/ecosystem/accio.png",
    ecosystemGbce: "/images/programa/ecosystem/gbce.png",
    ecosystemItec: "/images/programa/ecosystem/itec.png",
    ecosystemDih4cat: "/images/programa/ecosystem/dih4cat.png",
    ecosystemIese: "/images/programa/ecosystem/iese.png",
    ecosystemBarcelonaContechHub: "/images/programa/ecosystem/barcelona-contech-hub.png",
    ecosystemSngular: "/images/programa/ecosystem/sngular.png",
    ecosystemGoogleForStartups: "/images/programa/ecosystem/google-for-startups.png",
  },
} as const;
